# Goal: to build a CI/CD pipeline (just dummy )

name: CICD demo

on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
# CI -continous integration

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Show files
        run: ls -la
      
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build the code with Docker
        run: echo "Code built"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test the Docker image
        run: echo "Test passed"

# CD- Continous deployment/Delivery        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app on server
        run: echo "Application deployed"
   
