# My first GitHub Actions workflow

name: Hello

on:
  push:
   paths-ignore:
      - "README.md"
      - "docs/**"
   branches:
      - main
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello Doston"
  repo-name: 
      needs: greet
      runs-on: ubuntu-latest
      steps:
      - name: Show Repository Name
        run: echo "Repository name is ${{ github.event.repository.name }}" 
